export const ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
} as const;

export const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LEAVE: 'LEAVE',
  LATE: 'LATE',
} as const;

export const NOTIFICATION_TYPES = {
  ORDER: 'ORDER',
  SYSTEM: 'SYSTEM',
  PROMOTION: 'PROMOTION',
} as const;
